name: Auto Release Extension

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create clean release folder
        run: |
          mkdir release

          rsync -av \
            --exclude ".git" \
            --exclude ".github" \
            --exclude "update.ps1" \
            --exclude "node_modules" \
            --exclude "release" \
            ./ release/

      - name: Generate datetime version
        id: version
        run: |
          VERSION=$(date +'%Y%m%d-%H%M')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Zip release
        run: |
          cd release
          zip -r ../ckg-robot-chrome-extensions.zip .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: Release v${{ steps.version.outputs.version }}
          files: ckg-robot-chrome-extensions.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
